# Generated by Django 6.0.4 on 2026-04-17 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='intervenants',
            field=models.TextField(blank=True, verbose_name='Intervenants (un par ligne)'),
        ),
        migrations.AddField(
            model_name='event',
            name='programme',
            field=models.TextField(blank=True, verbose_name='Programme détaillé'),
        ),
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_nom', models.CharField(max_length=150, verbose_name="Nom de l'auteur")),
                ('auteur_email', models.EmailField(max_length=254, verbose_name="E-mail de l'auteur")),
                ('co_auteurs', models.TextField(blank=True, verbose_name='Co-auteurs (un par ligne)')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre du résumé')),
                ('type_soumission', models.CharField(choices=[('orale', 'Communication orale'), ('poster', 'Poster'), ('atelier', 'Atelier')], default='orale', max_length=20)),
                ('resume_texte', models.TextField(verbose_name='Résumé (texte)')),
                ('fichier', models.FileField(blank=True, upload_to='abstracts/%Y/', verbose_name='Fichier (PDF)')),
                ('mots_cles', models.CharField(blank=True, max_length=300, verbose_name='Mots-clés')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('revision', 'En révision')], default='soumis', max_length=20)),
                ('commentaire_comite', models.TextField(blank=True, verbose_name='Commentaire du comité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abstracts', to='events.event', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Résumé / Communication',
                'verbose_name_plural': 'Résumés / Communications',
                'ordering': ['-created_at'],
            },
        ),
    ]
