# Generated by Django 6.0.4 on 2026-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_intervenants_event_programme_abstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationScientifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500, verbose_name='Titre')),
                ('auteur', models.CharField(max_length=300, verbose_name='Auteur(s)')),
                ('type_presentation', models.CharField(choices=[('communication', 'Communication orale'), ('poster', 'Poster'), ('conference', 'Conférence / Panel / Symposium')], default='communication', max_length=20, verbose_name='Type de présentation')),
                ('theme', models.CharField(choices=[('communication_libre', 'Communication libre'), ('disponibilite_accessibilite', "Disponibilité et accessibilité de l'offre de santé"), ('ethique_qualite', 'Éthique et qualité des soins'), ('gestion_structures', 'Gestion des structures de soins'), ('numerique_sante', 'Numérique et santé maternelle et infantile'), ('nutrition', 'Nutrition maternelle et infantile'), ('planification_familiale', 'Planification familiale'), ('sante_mentale', 'Santé mentale du couple mère-enfant'), ('soins_nouveau_ne', 'Soins au nouveau-né (SMK, SENN…)'), ('soins_obstetricaux_sonu', "Soins obstétricaux et néonatals d'urgence (SONU)"), ('vaccination', "Vaccination de l'enfant et de la femme enceinte")], default='communication_libre', max_length=50, verbose_name='Thème')),
                ('fichier', models.FileField(blank=True, upload_to='publications/', verbose_name='Fichier PDF')),
                ('date_soumission', models.DateField(blank=True, null=True, verbose_name='Date de soumission')),
                ('congres', models.CharField(blank=True, default='7èmes JSP REMEHBS 2025', max_length=200, verbose_name='Congrès / Édition')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Communication scientifique',
                'verbose_name_plural': 'Communications scientifiques',
                'ordering': ['theme', 'ordre', 'auteur'],
            },
        ),
    ]
