# Generated by Django 6.0.4 on 2026-04-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_communication_scientifique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationscientifique',
            options={'ordering': ['-annee_congres', 'theme', 'ordre', 'auteur'], 'verbose_name': 'Communication scientifique', 'verbose_name_plural': 'Communications scientifiques'},
        ),
        migrations.AddField(
            model_name='communicationscientifique',
            name='annee_congres',
            field=models.IntegerField(choices=[(2009, '1ères JSP 2009'), (2011, '2èmes JSP 2011'), (2013, '3èmes JSP 2013'), (2015, '4èmes JSP 2015'), (2017, '5èmes JSP 2017'), (2019, '6èmes JSP 2019'), (2021, 'Édition spéciale 2021'), (2023, '7èmes JSP 2023'), (2025, '8èmes JSP 2025')], default=2025, verbose_name='Année du congrès'),
        ),
    ]
