# Generated by Django 6.0.4 on 2026-04-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID Transaction')),
                ('cinetpay_payment_token', models.CharField(blank=True, max_length=200)),
                ('montant', models.IntegerField(verbose_name='Montant (FCFA)')),
                ('statut', models.CharField(choices=[('initie', 'Initié'), ('succes', 'Succès'), ('echec', 'Échec'), ('annule', 'Annulé'), ('attente', 'En attente')], default='initie', max_length=20, verbose_name='Statut')),
                ('objet', models.CharField(max_length=200, verbose_name='Objet du paiement')),
                ('annee_cotisation', models.IntegerField(blank=True, null=True, verbose_name='Année cotisation')),
                ('payload_cinetpay', models.JSONField(blank=True, default=dict, verbose_name='Réponse CinetPay')),
                ('payment_url', models.URLField(blank=True, verbose_name='URL de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
