# Generated by Django 6.0.4 on 2026-04-17 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_membre', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom(s)')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('profession', models.CharField(max_length=150, verbose_name='Profession')),
                ('specialite', models.CharField(blank=True, max_length=150, verbose_name='Spécialité')),
                ('structure', models.CharField(blank=True, max_length=200, verbose_name='Structure / Établissement')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Province')),
                ('categorie', models.CharField(choices=[('etudiant', 'Étudiant / Stagiaire'), ('professionnel', 'Professionnel de Santé'), ('institution', 'Institution / Structure')], default='professionnel', max_length=20, verbose_name='Catégorie')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('radie', 'Radié')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_adhesion', models.DateField(blank=True, null=True, verbose_name="Date d'adhésion")),
                ('message', models.TextField(blank=True, verbose_name='Message / Motivations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('montant', models.IntegerField(verbose_name='Montant (FCFA)')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('impaye', 'Impayé'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('mode_paiement', models.CharField(blank=True, choices=[('orange_money', 'Orange Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('virement', 'Virement bancaire'), ('especes', 'Espèces')], max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence transaction')),
                ('recu_envoye', models.BooleanField(default=False, verbose_name='Reçu envoyé')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='members.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-annee'],
                'unique_together': {('member', 'annee')},
            },
        ),
    ]
