# Generated by Django 6.0.4 on 2026-04-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to='members/photos/%Y/', verbose_name='Photo de profil'),
        ),
    ]
